### ISSUE TITLE
`on_message` design

### ISSUE THREAD

**Issue by leonkozlowski** [themarathoncontinues/discord-trivia-bot#2]
https://github.com/themarathoncontinues/discord-trivia-bot/blob/506b507816ff27d43910115e0c88a7d91cbd241b/src/trivia_bot.py#L138

@jhikind there has to be a more elegant way to do this, maybe separating out into some private helpers-- also is there a way to globally `await` instead of checking if there is a message?

**Comment by jhikind** [comment]
private helps might work but I'm not sure how that would interact with the async and whether the methods have to be set up like they are right now. And what event would this global await check for?
